/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raihan09
 */
public class Win2_Frame extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Win1_Frame
     */
    public Win2_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1_frame2 = new javax.swing.JPanel();
        panel2_frame2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_nama_teknisi = new javax.swing.JLabel();
        txt_nama_teknisi = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        label_nomor_teknisi = new javax.swing.JLabel();
        txt_nomor_teknisi = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label_status = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_kerusakan = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        label_kerusakan = new javax.swing.JLabel();
        button_next2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        menu_statuspengerjaan = new javax.swing.JComboBox<>();
        button_back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel1_frame2.setBackground(new java.awt.Color(18, 51, 74));
        panel1_frame2.setForeground(new java.awt.Color(18, 51, 74));

        panel2_frame2.setBackground(new java.awt.Color(4, 39, 28));
        panel2_frame2.setForeground(new java.awt.Color(4, 39, 28));

        jLabel4.setFont(new java.awt.Font("Code Bold", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 242, 245));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SERVICE");

        jLabel5.setFont(new java.awt.Font("Code Bold", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 242, 245));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SDS");

        javax.swing.GroupLayout panel2_frame2Layout = new javax.swing.GroupLayout(panel2_frame2);
        panel2_frame2.setLayout(panel2_frame2Layout);
        panel2_frame2Layout.setHorizontalGroup(
            panel2_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_frame2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panel2_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panel2_frame2Layout.setVerticalGroup(
            panel2_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_frame2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_nama_teknisi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_teknisi.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_teknisi.setText("Nama Teknisi");

        txt_nama_teknisi.setBackground(new java.awt.Color(18, 51, 74));
        txt_nama_teknisi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_nama_teknisi.setForeground(new java.awt.Color(255, 255, 255));
        txt_nama_teknisi.setBorder(null);
        txt_nama_teknisi.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_nama_teknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_teknisiActionPerformed(evt);
            }
        });

        label_nomor_teknisi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nomor_teknisi.setForeground(new java.awt.Color(238, 242, 245));
        label_nomor_teknisi.setText("No. Telepon Teknisi");

        txt_nomor_teknisi.setBackground(new java.awt.Color(18, 51, 74));
        txt_nomor_teknisi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_nomor_teknisi.setForeground(new java.awt.Color(255, 255, 255));
        txt_nomor_teknisi.setBorder(null);
        txt_nomor_teknisi.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_nomor_teknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomor_teknisiActionPerformed(evt);
            }
        });

        label_status.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_status.setForeground(new java.awt.Color(238, 242, 245));
        label_status.setText("Status Perbaikan");

        txt_kerusakan.setBackground(new java.awt.Color(21, 40, 54));
        txt_kerusakan.setColumns(20);
        txt_kerusakan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_kerusakan.setForeground(new java.awt.Color(255, 255, 255));
        txt_kerusakan.setRows(5);
        txt_kerusakan.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txt_kerusakan);

        label_kerusakan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_kerusakan.setForeground(new java.awt.Color(238, 242, 245));
        label_kerusakan.setText("Semua Kerusakan");

        button_next2.setText("Save & Next");
        button_next2.setBorder(null);

        menu_statuspengerjaan.setBackground(new java.awt.Color(21, 40, 54));
        menu_statuspengerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Dikerjakan", "Sedang Dikerjakan" }));
        menu_statuspengerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_statuspengerjaanActionPerformed(evt);
            }
        });

        button_back1.setText("Back");
        button_back1.setBorder(null);
        button_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1_frame2Layout = new javax.swing.GroupLayout(panel1_frame2);
        panel1_frame2.setLayout(panel1_frame2Layout);
        panel1_frame2Layout.setHorizontalGroup(
            panel1_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1_frame2Layout.createSequentialGroup()
                .addComponent(panel2_frame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addGroup(panel1_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel1_frame2Layout.createSequentialGroup()
                            .addComponent(button_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_next2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(label_nama_teknisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nama_teknisi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_nomor_teknisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nomor_teknisi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_kerusakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menu_statuspengerjaan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        panel1_frame2Layout.setVerticalGroup(
            panel1_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2_frame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1_frame2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(label_nama_teknisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nama_teknisi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_nomor_teknisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomor_teknisi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_status, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_statuspengerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(panel1_frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_next2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1_frame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1_frame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nama_teknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_teknisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_teknisiActionPerformed

    private void txt_nomor_teknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomor_teknisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomor_teknisiActionPerformed

    private void button_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_back1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_back1ActionPerformed

    private void menu_statuspengerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_statuspengerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_statuspengerjaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Win1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Win1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Win1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Win1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Win1_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_back1;
    private javax.swing.JButton button_next2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label_kerusakan;
    private javax.swing.JLabel label_nama_teknisi;
    private javax.swing.JLabel label_nomor_teknisi;
    private javax.swing.JLabel label_status;
    private javax.swing.JComboBox<String> menu_statuspengerjaan;
    private javax.swing.JPanel panel1_frame2;
    private javax.swing.JPanel panel2_frame2;
    private javax.swing.JTextArea txt_kerusakan;
    private javax.swing.JTextField txt_nama_teknisi;
    private javax.swing.JTextField txt_nomor_teknisi;
    // End of variables declaration//GEN-END:variables
}
