/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raihan09
 */
public class Window1 extends javax.swing.JFrame {

    /**
     * Creates new form Window1
     */
    public Window1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel1 = new javax.swing.JPanel();
        label_nama_pelanggan = new javax.swing.JLabel();
        txt_nama_pelanggan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        label_nomor_pelanggan = new javax.swing.JLabel();
        txt_nomor_pelanggan = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label_tipehp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_kendala = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_tipehp = new javax.swing.JTextArea();
        label_kendala = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        label_nama_pelanggan1 = new javax.swing.JLabel();
        txt_tgl_masuk = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        label_nama_pelanggan2 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        label_status = new javax.swing.JLabel();
        label_kerusakan = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_kerusakan = new javax.swing.JTextArea();
        jSeparator8 = new javax.swing.JSeparator();
        menu_statuspengerjaan = new javax.swing.JComboBox<>();
        panel3 = new javax.swing.JPanel();
        panel_login = new javax.swing.JPanel();
        label_login_user = new javax.swing.JLabel();
        txt_login_user = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txt_login_pass = new javax.swing.JTextField();
        label_login_pass = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        SERVICE = new javax.swing.JLabel();
        SDS = new javax.swing.JLabel();
        button_panel1 = new javax.swing.JButton();
        button_panel2 = new javax.swing.JButton();
        button_panel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BackPanel.setBackground(new java.awt.Color(4, 39, 28));

        panel1.setBackground(new java.awt.Color(18, 51, 74));

        label_nama_pelanggan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan.setText("Nama");

        txt_nama_pelanggan.setBackground(new java.awt.Color(18, 51, 74));
        txt_nama_pelanggan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_nama_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        txt_nama_pelanggan.setBorder(null);
        txt_nama_pelanggan.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_pelangganActionPerformed(evt);
            }
        });

        label_nomor_pelanggan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nomor_pelanggan.setForeground(new java.awt.Color(238, 242, 245));
        label_nomor_pelanggan.setText("No. Telepon");

        txt_nomor_pelanggan.setBackground(new java.awt.Color(18, 51, 74));
        txt_nomor_pelanggan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_nomor_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        txt_nomor_pelanggan.setBorder(null);
        txt_nomor_pelanggan.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_nomor_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomor_pelangganActionPerformed(evt);
            }
        });

        label_tipehp.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_tipehp.setForeground(new java.awt.Color(238, 242, 245));
        label_tipehp.setText("Merek dan Tipe HP");

        txt_kendala.setBackground(new java.awt.Color(21, 40, 54));
        txt_kendala.setColumns(20);
        txt_kendala.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_kendala.setForeground(new java.awt.Color(255, 255, 255));
        txt_kendala.setRows(5);
        txt_kendala.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txt_kendala);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt_tipehp.setBackground(new java.awt.Color(21, 40, 54));
        txt_tipehp.setColumns(20);
        txt_tipehp.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_tipehp.setForeground(new java.awt.Color(255, 255, 255));
        txt_tipehp.setRows(5);
        txt_tipehp.setToolTipText("Contoh : Samsung Galaxy S20 Ultra");
        txt_tipehp.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txt_tipehp);

        label_kendala.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_kendala.setForeground(new java.awt.Color(238, 242, 245));
        label_kendala.setText("Kendala Kerusakan");

        label_nama_pelanggan1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan1.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan1.setText("Tanggal Masuk");

        txt_tgl_masuk.setBackground(new java.awt.Color(18, 51, 74));
        txt_tgl_masuk.setForeground(new java.awt.Color(255, 255, 255));
        txt_tgl_masuk.setToolTipText("contoh : 21-05-2020");
        txt_tgl_masuk.setBorder(null);

        label_nama_pelanggan2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan2.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan2.setText("Contoh : 20-04-2020");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nama_pelanggan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_tgl_masuk)
                    .addComponent(jSeparator5)
                    .addComponent(label_nama_pelanggan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nama_pelanggan)
                    .addComponent(jSeparator1)
                    .addComponent(label_nomor_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nomor_pelanggan)
                    .addComponent(jSeparator2)
                    .addComponent(label_tipehp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_kendala, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(label_nama_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txt_nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_nama_pelanggan1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nomor_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txt_nomor_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txt_tgl_masuk)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_kendala, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tipehp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        panel2.setBackground(new java.awt.Color(18, 51, 74));

        label_status.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_status.setForeground(new java.awt.Color(238, 242, 245));
        label_status.setText("Status Perbaikan");

        label_kerusakan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_kerusakan.setForeground(new java.awt.Color(238, 242, 245));
        label_kerusakan.setText("Semua Kerusakan");

        txt_kerusakan.setBackground(new java.awt.Color(21, 40, 54));
        txt_kerusakan.setColumns(20);
        txt_kerusakan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_kerusakan.setForeground(new java.awt.Color(255, 255, 255));
        txt_kerusakan.setRows(5);
        txt_kerusakan.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(txt_kerusakan);

        menu_statuspengerjaan.setBackground(new java.awt.Color(21, 40, 54));
        menu_statuspengerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Dikerjakan", "Sedang Dikerjakan" }));
        menu_statuspengerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_statuspengerjaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(label_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_kerusakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menu_statuspengerjaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(label_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_status, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_statuspengerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        panel3.setBackground(new java.awt.Color(18, 51, 74));
        panel3.setPreferredSize(new java.awt.Dimension(586, 510));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        panel_login.setBackground(new java.awt.Color(18, 51, 74));
        panel_login.setPreferredSize(new java.awt.Dimension(586, 510));

        label_login_user.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_login_user.setForeground(new java.awt.Color(238, 242, 245));
        label_login_user.setText("Username");

        txt_login_user.setBackground(new java.awt.Color(18, 51, 74));
        txt_login_user.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_login_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_login_user.setBorder(null);
        txt_login_user.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_login_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_userActionPerformed(evt);
            }
        });

        txt_login_pass.setBackground(new java.awt.Color(18, 51, 74));
        txt_login_pass.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_login_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_login_pass.setBorder(null);
        txt_login_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_login_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_login_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_passActionPerformed(evt);
            }
        });

        label_login_pass.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_login_pass.setForeground(new java.awt.Color(238, 242, 245));
        label_login_pass.setText("Password");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6)
                    .addComponent(txt_login_user)
                    .addComponent(label_login_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator9)
                    .addComponent(txt_login_pass)
                    .addComponent(label_login_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(panel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panel_login, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SERVICE.setFont(new java.awt.Font("Code Bold", 1, 24)); // NOI18N
        SERVICE.setForeground(new java.awt.Color(238, 242, 245));
        SERVICE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SERVICE.setText("SERVICE");

        SDS.setFont(new java.awt.Font("Code Bold", 1, 24)); // NOI18N
        SDS.setForeground(new java.awt.Color(238, 242, 245));
        SDS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SDS.setText("SDS");

        button_panel1.setText("Service");
        button_panel1.setBorder(null);
        button_panel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_panel1ActionPerformed(evt);
            }
        });

        button_panel2.setText("Admin");
        button_panel2.setBorder(null);
        button_panel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_panel2ActionPerformed(evt);
            }
        });

        button_panel3.setText("Receipt");
        button_panel3.setBorder(null);
        button_panel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_panel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SERVICE, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(button_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(SDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SERVICE)
                .addGap(93, 93, 93)
                .addComponent(button_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_panel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_panel3ActionPerformed
        // TODO add your handling code here:
        panel1.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(true);
    }//GEN-LAST:event_button_panel3ActionPerformed

    private void txt_nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_pelangganActionPerformed

    private void txt_nomor_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomor_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomor_pelangganActionPerformed

    private void button_panel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_panel1ActionPerformed
        // TODO add your handling code here:
        panel1.setVisible(true);
        panel2.setVisible(false);
        panel3.setVisible(false);
    }//GEN-LAST:event_button_panel1ActionPerformed

    private void button_panel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_panel2ActionPerformed
        // TODO add your handling code here:
        panel1.setVisible(false);
        panel2.setVisible(true);
        panel3.setVisible(false);
    }//GEN-LAST:event_button_panel2ActionPerformed

    private void menu_statuspengerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_statuspengerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_statuspengerjaanActionPerformed

    private void txt_login_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_userActionPerformed

    private void txt_login_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_passActionPerformed
//        txt_login_pass.setEcho
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JLabel SDS;
    private javax.swing.JLabel SERVICE;
    private javax.swing.JButton button_panel1;
    private javax.swing.JButton button_panel2;
    private javax.swing.JButton button_panel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel label_kendala;
    private javax.swing.JLabel label_kerusakan;
    private javax.swing.JLabel label_login_pass;
    private javax.swing.JLabel label_login_user;
    private javax.swing.JLabel label_nama_pelanggan;
    private javax.swing.JLabel label_nama_pelanggan1;
    private javax.swing.JLabel label_nama_pelanggan2;
    private javax.swing.JLabel label_nomor_pelanggan;
    private javax.swing.JLabel label_status;
    private javax.swing.JLabel label_tipehp;
    private javax.swing.JComboBox<String> menu_statuspengerjaan;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel_login;
    private javax.swing.JTextArea txt_kendala;
    private javax.swing.JTextArea txt_kerusakan;
    private javax.swing.JTextField txt_login_pass;
    private javax.swing.JTextField txt_login_user;
    private javax.swing.JTextField txt_nama_pelanggan;
    private javax.swing.JTextField txt_nomor_pelanggan;
    private javax.swing.JTextField txt_tgl_masuk;
    private javax.swing.JTextArea txt_tipehp;
    // End of variables declaration//GEN-END:variables
}
