/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raihan09
 */

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
//import kereta.Dashboard;
//import static kereta.Login.level;
//import static kereta.Login.username;



public class Window1 extends javax.swing.JFrame {
//    

    /**
     * Creates new form Window1
     */
    public Window1() {
        initComponents();
//        first_panel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_first = new javax.swing.JPanel();
        label_login_user1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        panel1 = new javax.swing.JPanel();
        label_nama_pelanggan = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        label_nomor_pelanggan = new javax.swing.JLabel();
        no_telepon = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label_tipehp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        penyebab = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        merk_hp = new javax.swing.JTextArea();
        label_kendala = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        label_nama_pelanggan1 = new javax.swing.JLabel();
        tanggal_masuk = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        label_nama_pelanggan2 = new javax.swing.JLabel();
        button_panel4 = new javax.swing.JButton();
        panel_login = new javax.swing.JPanel();
        label_login_user = new javax.swing.JLabel();
        txt_login_user = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txt_login_pass = new javax.swing.JTextField();
        label_login_pass = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        button_login = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel3 = new javax.swing.JPanel();
        label_nama_pelanggan3 = new javax.swing.JLabel();
        label_nama_pelanggan4 = new javax.swing.JLabel();
        label_nama_pelanggan5 = new javax.swing.JLabel();
        label_nama_pelanggan6 = new javax.swing.JLabel();
        label_nama_pelanggan7 = new javax.swing.JLabel();
        label_nama_pelanggan8 = new javax.swing.JLabel();
        label_nama_pelanggan9 = new javax.swing.JLabel();
        label_nama_pelanggan10 = new javax.swing.JLabel();
        label_nama_pelanggan11 = new javax.swing.JLabel();
        label_nama_pelanggan12 = new javax.swing.JLabel();
        label_nama_pelanggan13 = new javax.swing.JLabel();
        label_nama_pelanggan14 = new javax.swing.JLabel();
        label_nama_pelanggan15 = new javax.swing.JLabel();
        label_nama_pelanggan16 = new javax.swing.JLabel();
        label_nama_pelanggan17 = new javax.swing.JLabel();
        label_nama_pelanggan18 = new javax.swing.JLabel();
        label_nama_pelanggan19 = new javax.swing.JLabel();
        label_nama_pelanggan20 = new javax.swing.JLabel();
        label_nama_pelanggan21 = new javax.swing.JLabel();
        label_nama_pelanggan22 = new javax.swing.JLabel();
        label_nama_pelanggan23 = new javax.swing.JLabel();
        SERVICE = new javax.swing.JLabel();
        SDS = new javax.swing.JLabel();
        button_panel1 = new javax.swing.JButton();
        button_panel2 = new javax.swing.JButton();
        button_panel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BackPanel.setBackground(new java.awt.Color(4, 39, 28));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        panel_first.setBackground(new java.awt.Color(18, 51, 74));
        panel_first.setPreferredSize(new java.awt.Dimension(627, 532));

        label_login_user1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_login_user1.setForeground(new java.awt.Color(238, 242, 245));
        label_login_user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_login_user1.setText("Welcome");

        javax.swing.GroupLayout panel_firstLayout = new javax.swing.GroupLayout(panel_first);
        panel_first.setLayout(panel_firstLayout);
        panel_firstLayout.setHorizontalGroup(
            panel_firstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_firstLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(panel_firstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_login_user1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jSeparator7))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panel_firstLayout.setVerticalGroup(
            panel_firstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_firstLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(label_login_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_first, "card2");

        panel1.setBackground(new java.awt.Color(18, 51, 74));

        label_nama_pelanggan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan.setText("Nama");

        nama_pelanggan.setBackground(new java.awt.Color(18, 51, 74));
        nama_pelanggan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nama_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        nama_pelanggan.setBorder(null);
        nama_pelanggan.setCaretColor(new java.awt.Color(255, 255, 255));
        nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pelangganActionPerformed(evt);
            }
        });

        label_nomor_pelanggan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nomor_pelanggan.setForeground(new java.awt.Color(238, 242, 245));
        label_nomor_pelanggan.setText("No. Telepon");

        no_telepon.setBackground(new java.awt.Color(18, 51, 74));
        no_telepon.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        no_telepon.setForeground(new java.awt.Color(255, 255, 255));
        no_telepon.setBorder(null);
        no_telepon.setCaretColor(new java.awt.Color(255, 255, 255));
        no_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_teleponActionPerformed(evt);
            }
        });

        label_tipehp.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_tipehp.setForeground(new java.awt.Color(238, 242, 245));
        label_tipehp.setText("Merek dan Tipe HP");

        penyebab.setBackground(new java.awt.Color(21, 40, 54));
        penyebab.setColumns(20);
        penyebab.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        penyebab.setForeground(new java.awt.Color(255, 255, 255));
        penyebab.setRows(5);
        penyebab.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(penyebab);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        merk_hp.setBackground(new java.awt.Color(21, 40, 54));
        merk_hp.setColumns(20);
        merk_hp.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        merk_hp.setForeground(new java.awt.Color(255, 255, 255));
        merk_hp.setRows(5);
        merk_hp.setToolTipText("Contoh : Samsung Galaxy S20 Ultra");
        merk_hp.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(merk_hp);

        label_kendala.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_kendala.setForeground(new java.awt.Color(238, 242, 245));
        label_kendala.setText("Kendala Kerusakan");

        label_nama_pelanggan1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan1.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan1.setText("Tanggal Masuk");

        tanggal_masuk.setBackground(new java.awt.Color(18, 51, 74));
        tanggal_masuk.setForeground(new java.awt.Color(255, 255, 255));
        tanggal_masuk.setToolTipText("contoh : 21-05-2020");
        tanggal_masuk.setBorder(null);
        tanggal_masuk.setCaretColor(new java.awt.Color(255, 255, 255));

        label_nama_pelanggan2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan2.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan2.setText("Contoh : 2020-04-20");

        button_panel4.setText("Save");
        button_panel4.setBorder(null);
        button_panel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_panel4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggal_masuk)
                            .addComponent(jSeparator5)
                            .addComponent(label_nama_pelanggan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(label_nama_pelanggan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama_pelanggan)
                            .addComponent(jSeparator1)
                            .addComponent(label_nomor_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(no_telepon)
                            .addComponent(jSeparator2)
                            .addComponent(label_tipehp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_kendala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(label_nama_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nomor_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label_nama_pelanggan1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nama_pelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggal_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_kendala, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tipehp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(button_panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLayeredPane1.add(panel1, "card3");

        panel_login.setBackground(new java.awt.Color(18, 51, 74));
        panel_login.setPreferredSize(new java.awt.Dimension(627, 532));

        label_login_user.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_login_user.setForeground(new java.awt.Color(238, 242, 245));
        label_login_user.setText("Username");

        txt_login_user.setBackground(new java.awt.Color(18, 51, 74));
        txt_login_user.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_login_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_login_user.setBorder(null);
        txt_login_user.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_login_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_userActionPerformed(evt);
            }
        });

        txt_login_pass.setBackground(new java.awt.Color(18, 51, 74));
        txt_login_pass.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_login_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_login_pass.setBorder(null);
        txt_login_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_login_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_login_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_passActionPerformed(evt);
            }
        });

        label_login_pass.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_login_pass.setForeground(new java.awt.Color(238, 242, 245));
        label_login_pass.setText("Password");

        button_login.setText("Login");
        button_login.setBorder(null);
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_loginLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_login_user, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_login_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_login_pass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_login_pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_login, "card4");

        panel2.setBackground(new java.awt.Color(18, 51, 74));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Pelanggan", "Merek HP", "Kendala", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel2, "card5");

        panel3.setBackground(new java.awt.Color(18, 51, 74));

        label_nama_pelanggan3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan3.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan3.setText("Nama");

        label_nama_pelanggan4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan4.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan4.setText(":");

        label_nama_pelanggan5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan5.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan5.setText("Kerusakan");

        label_nama_pelanggan6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan6.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan6.setText("Nama Teknisi");

        label_nama_pelanggan7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan7.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan7.setText("Device");

        label_nama_pelanggan8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan8.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan8.setText(":");

        label_nama_pelanggan9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan9.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan9.setText(":");

        label_nama_pelanggan10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan10.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan10.setText(":");

        label_nama_pelanggan11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan11.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan11.setText("Tanggal Masuk");

        label_nama_pelanggan12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan12.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan12.setText(":");

        label_nama_pelanggan13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan13.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan13.setText("Tanggal Selesai");

        label_nama_pelanggan14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan14.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan14.setText(":");

        label_nama_pelanggan15.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        label_nama_pelanggan15.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan15.setText("var_price");

        label_nama_pelanggan16.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        label_nama_pelanggan16.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan16.setText(":");

        label_nama_pelanggan17.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        label_nama_pelanggan17.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan17.setText("Total Biaya");

        label_nama_pelanggan18.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan18.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan18.setText("var_nama");

        label_nama_pelanggan19.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan19.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan19.setText("var_tglsel");

        label_nama_pelanggan20.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan20.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan20.setText("var_device");

        label_nama_pelanggan21.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan21.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan21.setText("var_tglmsk");

        label_nama_pelanggan22.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan22.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan22.setText("var_kerusakan");

        label_nama_pelanggan23.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label_nama_pelanggan23.setForeground(new java.awt.Color(238, 242, 245));
        label_nama_pelanggan23.setText("var_namateknisi");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_nama_pelanggan17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nama_pelanggan16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nama_pelanggan15, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nama_pelanggan3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_nama_pelanggan7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(label_nama_pelanggan8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_nama_pelanggan20, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(label_nama_pelanggan4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_nama_pelanggan18, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(label_nama_pelanggan5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan22, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(label_nama_pelanggan6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan23, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(label_nama_pelanggan11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan21, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(label_nama_pelanggan13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nama_pelanggan19, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_pelanggan3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_pelanggan7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_pelanggan6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_pelanggan5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_pelanggan11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_pelanggan13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_pelanggan16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pelanggan15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel3, "card6");

        SERVICE.setFont(new java.awt.Font("Code Bold", 1, 24)); // NOI18N
        SERVICE.setForeground(new java.awt.Color(238, 242, 245));
        SERVICE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SERVICE.setText("SERVICE");

        SDS.setFont(new java.awt.Font("Code Bold", 1, 24)); // NOI18N
        SDS.setForeground(new java.awt.Color(238, 242, 245));
        SDS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SDS.setText("SDS");

        button_panel1.setText("Service");
        button_panel1.setBorder(null);
        button_panel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_panel1ActionPerformed(evt);
            }
        });

        button_panel2.setText("Admin");
        button_panel2.setBorder(null);
        button_panel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_panel2ActionPerformed(evt);
            }
        });

        button_panel3.setText("Receipt");
        button_panel3.setBorder(null);
        button_panel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_panel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SERVICE, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(button_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(SDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SERVICE)
                .addGap(93, 93, 93)
                .addComponent(button_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void showfirstpanel()
//    {
//        
//        
//    }
//    
    
    
    
    private void nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pelangganActionPerformed

    private void no_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_teleponActionPerformed

    private void button_panel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_panel1ActionPerformed
        // TODO add your handling code here:
        
        panel1.setVisible(true);
        panel_login.setVisible(false);
        panel_first.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(false);
    }//GEN-LAST:event_button_panel1ActionPerformed

    private void txt_login_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_userActionPerformed

    private void txt_login_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_passActionPerformed
//        txt_login_pass.setEcho
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_passActionPerformed

    private void button_panel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_panel2ActionPerformed
        // TODO add your handling code here:
        panel1.setVisible(false);
        panel_login.setVisible(true);
        panel_first.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(false);
        
    }//GEN-LAST:event_button_panel2ActionPerformed

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        // TODO add your handling code here:
        
        String sql = "SELECT * FROM admin where username=? and password =?";
        
        
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tubes","root","");
            
            PreparedStatement psmt = con.prepareStatement(sql);
            psmt.setString(1,txt_login_user.getText());
            psmt.setString(2,txt_login_pass.getText());
            
            ResultSet rs = psmt.executeQuery();
            
            
            if(rs.next())
            {
                
                
                panel1.setVisible(false);
                panel_first.setVisible(false);
                panel2.setVisible(true);
                panel_login.setVisible(false);
                panel3.setVisible(false);
                
            }
            con.close();
            
            
        
//        String username = txt_login_user.getText();

        
            
            
            
            
                //old login
//            Login fungsi = new Login();
//            fungsi.login();
//            fungsi.pst.setString(1, txt_login_user.getText());
//            fungsi.pst.setString(2, txt_login_pass.getText());
//            ResultSet rs = fungsi.pst.executeQuery();
        
            
                
                
//                if(level == 1)
//                {
////                jOptionPane1.showMessageDialog(null,"Login Berhasil");
//                Dashboard dashboard = new Dashboard();
//                dashboard.setVisible(true);
//                this.dispose();
//                }
//                
//                else if(level == 2){
//                jOptionPane1.showMessageDialog(null,"Login Berhasil");
//                Dashboard test = new Dashboard();
//                
//                test.setVisible(true);
//                this.dispose();
//                }
//            }
//            else{
//                jOptionPane1.showMessageDialog(null,"Login Gagal");
//                jTextField1.setText("");
//                jTextField2.setText("");
//            }
            
//            fungsi.con.close();
        }
        catch(Exception e)
        {
            
        }
        
           
        
        
        
    }//GEN-LAST:event_button_loginActionPerformed

    private void button_panel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_panel3ActionPerformed
        // TODO add your handling code here:
        panel1.setVisible(false);
        panel_login.setVisible(false);
        panel_first.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(true);
    }//GEN-LAST:event_button_panel3ActionPerformed

    private void button_panel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_panel4ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tubes","root","");
            
            String sql = "insert into pelanggan values (?, ?, ?, ?, ?)";
            PreparedStatement psmt = con.prepareStatement(sql);
            psmt.setString(1, nama_pelanggan.getText());
            psmt.setString(2, no_telepon.getText());
            psmt.setString(3, penyebab.getText());
            psmt.setString(4, merk_hp.getText());
            psmt.setString(5, tanggal_masuk.getText());
            
            psmt.executeUpdate();
            con.close();
                    
                    
        }
        catch(Exception e)
        {
            
        }
                
                                   
               
                
    }//GEN-LAST:event_button_panel4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window1().setVisible(true);
                
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JLabel SDS;
    private javax.swing.JLabel SERVICE;
    private javax.swing.JButton button_login;
    private javax.swing.JButton button_panel1;
    private javax.swing.JButton button_panel2;
    private javax.swing.JButton button_panel3;
    private javax.swing.JButton button_panel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_kendala;
    private javax.swing.JLabel label_login_pass;
    private javax.swing.JLabel label_login_user;
    private javax.swing.JLabel label_login_user1;
    private javax.swing.JLabel label_nama_pelanggan;
    private javax.swing.JLabel label_nama_pelanggan1;
    private javax.swing.JLabel label_nama_pelanggan10;
    private javax.swing.JLabel label_nama_pelanggan11;
    private javax.swing.JLabel label_nama_pelanggan12;
    private javax.swing.JLabel label_nama_pelanggan13;
    private javax.swing.JLabel label_nama_pelanggan14;
    private javax.swing.JLabel label_nama_pelanggan15;
    private javax.swing.JLabel label_nama_pelanggan16;
    private javax.swing.JLabel label_nama_pelanggan17;
    private javax.swing.JLabel label_nama_pelanggan18;
    private javax.swing.JLabel label_nama_pelanggan19;
    private javax.swing.JLabel label_nama_pelanggan2;
    private javax.swing.JLabel label_nama_pelanggan20;
    private javax.swing.JLabel label_nama_pelanggan21;
    private javax.swing.JLabel label_nama_pelanggan22;
    private javax.swing.JLabel label_nama_pelanggan23;
    private javax.swing.JLabel label_nama_pelanggan3;
    private javax.swing.JLabel label_nama_pelanggan4;
    private javax.swing.JLabel label_nama_pelanggan5;
    private javax.swing.JLabel label_nama_pelanggan6;
    private javax.swing.JLabel label_nama_pelanggan7;
    private javax.swing.JLabel label_nama_pelanggan8;
    private javax.swing.JLabel label_nama_pelanggan9;
    private javax.swing.JLabel label_nomor_pelanggan;
    private javax.swing.JLabel label_tipehp;
    private javax.swing.JTextArea merk_hp;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JTextField no_telepon;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel_first;
    private javax.swing.JPanel panel_login;
    private javax.swing.JTextArea penyebab;
    private javax.swing.JTextField tanggal_masuk;
    private javax.swing.JTextField txt_login_pass;
    private javax.swing.JTextField txt_login_user;
    // End of variables declaration//GEN-END:variables
}
